# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------

[hugoVersion]
min = "0.161.0"

[[imports]]
path = "github.com/hugo-fixit/fixit-bundle"
version = "v1.6.9"
